export default [
  {
    name: 'simCardsInStock',
    labelKey: 'indicators.getparc.lines.availableSIMCards',
    color: 'text-success',
    clickable: true,
    total: '-',
    roles: ['PARTNER'],
    filters: [],
    fetchKey: 'SIM_NOT_PREACTIVATED',
  },
  {
    name: 'allocatedSIMCards',
    labelKey: 'indicators.getparc.lines.allocatedSIMCards',
    color: 'text-success',
    clickable: true,
    total: '-',
    roles: ['PARTNER'],
    fetchKey: 'SIM_PREACTIVATED',
  },
  {
    name: 'activatedSIMCards',
    labelKey: 'indicators.getparc.lines.activatedSIMCards',
    color: 'text-success',
    clickable: true,
    total: '-',
    roles: ['PARTNER'],
    fetchKey: 'SIM_ACTIVATED',
  },
  {
    name: 'suspended',
    labelKey: 'indicators.getparc.lines.suspended',
    color: 'text-warning',
    clickable: true,
    total: '-',
    roles: ['BO', 'PARTNER'],
    fetchKey: 'SIM_SUSPENDED',
  },
  {
    name: 'traffic',
    labelKey: 'indicators.getparc.lines.traffic',
    color: 'text-warning',
    clickable: true,
    total: '-',
    roles: ['BO'],

    fetchKey: 'SIM_TRAFFICKING',
  },
];
