image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/gradle:5.1.1

stages:
  - version
  - unitTests
  - build
  - test
  - release
  - deploy
  - undeploy

variables:
  http_proxy: "http://proxyace2.prod.extelia.fr:8080"
  https_proxy: "http://proxyace2.prod.extelia.fr:8080"
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048M" -Dorg.gradle.daemon=false -Djib.httpTimeout=120000 -Dhttp.proxyHost=proxyace2.prod.extelia.fr -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxyace2.prod.extelia.fr -Dhttps.proxyPort=8080
  ORG_GRADLE_PROJECT_npmBuildEnv: integration # integration ou full-local. Sans valeur, c'est la production qui est cible
  GSG_RELEASE_BRANCHES: uat
  GSG_PRE_TMPL: '{{ (env "CI_COMMIT_REF_SLUG") }},{{ seq }}'
  GSG_BUILD_TMPL: '{{ commitTS.Format "20060102150405" }}'
  GSG_INITIAL_DEVELOPMENT: "false"
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  # - echo "registry=https://outils.docapost.tech/nexus/repository/npm-central/" > ~/.npmrc

version:
  stage: version
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.20.4
  script:
    - >
      if [[ $CI_COMMIT_REF_NAME == \hotfix* ]]; then
        echo "Calculating version for hotfix branch"
        sed 's/_\(.*\)//' ui-server/version.txt | sed '$s/$/'"_$CI_COMMIT_REF_SLUG"'/' > .next-version
      else
        echo "Calculating version for branch $CI_COMMIT_REF_NAME"
        release next-version --allow-current > .next-version
      fi
  after_script:
    - cat .next-version
    - cp /usr/bin/release .
  artifacts:
    paths:
      - .next-version
      - release
  except:
    - tags
    - schedules
  interruptible: true

unitTests:
  stage: unitTests
  script:
    - gradle :ui:frontUnitTests --info
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle/caches
      - ui/.gradle/nodejs
      - ui/.gradle/yarn
      - ui/node_modules
      - cache/Cypress
      - .cache/Cypress
  except:
    - tags
    - schedules
  interruptible: true

build:
  stage: build
  script:
    - gradle --build-cache assemble --info
    - echo "RELEASE_SHA=$CI_COMMIT_SHA" >> build_info
    - echo "RELEASE_VERSION=`cat .next-version`" >> build_info
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle/caches
      - ui/.gradle/nodejs
      - ui/.gradle/yarn
      - ui/node_modules
      - cache/Cypress
      - .cache/Cypress
  artifacts:
    paths:
      - build_info
      - ui/dist
  except:
    - tags
    - schedules
  interruptible: true

pre-release:
  stage: release
  script:
    - rm -f ui-server/version.txt
    - cp .next-version ui-server/version.txt
    - rm -f ui-server/pre_release_info
    - cp build_info ui-server/pre_release_info
    - . ui-server/pre_release_info
    - gradle --build-cache jib -PregistryImageName=$CI_REGISTRY_IMAGE -PregistryImageTag=latest -PregistryUsername=$CI_REGISTRY_USER -PregistryPassword=$CI_REGISTRY_PASSWORD --info
    - ./release -v
    - ./release changelog --f ui-server/CHANGELOG.md
    - ./release commit-and-tag ui-server/CHANGELOG.md ui-server/pre_release_info ui-server/version.txt
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - .gradle/caches
      - ui/.gradle/nodejs
      - ui/.gradle/yarn
      - ui/node_modules
      - cache/Cypress
      - .cache/Cypress

  only:
    - master
  except:
    - tags
    - schedules

release:
  stage: release
  script:
    - rm -f ui-server/version.txt
    - cp .next-version ui-server/version.txt
    - rm -f ui-server/release_info
    - cp build_info ui-server/release_info
    - . ui-server/release_info
    - gradle --build-cache jib -PregistryImageName=$CI_REGISTRY_IMAGE -PregistryUsername=$CI_REGISTRY_USER -PregistryPassword=$CI_REGISTRY_PASSWORD --info
    - ./release -v
    - ./release changelog --f ui-server/CHANGELOG.md
    - ./release commit-and-tag ui-server/CHANGELOG.md ui-server/release_info ui-server/version.txt
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle/caches
      - ui/.gradle/nodejs
      - ui/.gradle/yarn
      - ui/node_modules
      - .cache/Cypress
      - cache/Cypress
  only:
    - uat
    - /^hotfix_.*$/
  except:
    - tags
    - schedules

deploy_integration:
  stage: deploy
  image: m2m-registry.by-docapost.com/powwow-ng/envs/toolbox
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan powwowng1.zone.local >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh m2m-prd@powwowng1.zone.local "bash --login -c 'export SPRING_PROFILE=int && ~/docker/docker-admin.sh restart'"
  environment:
    name: integration
    url: http://powwowng1.zone.local:8080
  only:
    - master
  dependencies: []
  resource_group: integration
  except:
    - schedules

deploy_testing:
  stage: deploy
  image: m2m-registry.by-docapost.com/powwow-ng/envs/toolbox
  variables:
    KUBECONFIG: /etc/deploy/config
  before_script:
    - mkdir -p /etc/deploy
    - echo ${KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
    - kubectl config view -o jsonpath='{.contexts[*].name}' | tr " " "\n"
    - kubectl config use-context m2m-node-tst
  script:
    - kubectl get po
    - kubectl patch deployment ui -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%Y%m%d%H%M%S'`\"}}}}}"
    - kubectl rollout status deployment.v1.apps/ui
  when: manual
  environment:
    name: testing
    url: http://172.20.157.115:8080
  only:
    - master
  dependencies: []
  resource_group: test
  except:
    - schedules

deploy_uat:
  stage: deploy
  image: m2m-registry.by-docapost.com/powwow-ng/envs/toolbox
  variables:
    KUBECONFIG: /etc/deploy/config
  before_script:
    - mkdir -p /etc/deploy
    - echo ${KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
    - kubectl config view -o jsonpath='{.contexts[*].name}' | tr " " "\n"
    - kubectl config use-context m2m-node-uat

  script:
    - kubectl get po
    - . build_info
    - echo $RELEASE_VERSION
    - kubectl set image deployments/ui ui=$CI_REGISTRY_IMAGE:$RELEASE_VERSION --record=true
  when: manual
  environment:
    name: uat
    url: https://m2m-uat.by-docapost.com
  only:
    - uat
  except:
    - tags
    - schedules
  resource_group: uat

undeploy_uat:
  stage: undeploy
  image: m2m-registry.by-docapost.com/powwow-ng/envs/toolbox
  variables:
    KUBECONFIG: /etc/deploy/config
  before_script:
    - mkdir -p /etc/deploy
    - echo ${KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
    - kubectl config view -o jsonpath='{.contexts[*].name}' | tr " " "\n"
    - kubectl config use-context m2m-node-uat
  script:
    - kubectl get po
    - kubectl rollout history deployment/ui
    - kubectl rollout undo deployment/ui
  when: manual
  environment:
    name: uat
    url: https://m2m-uat.by-docapost.com
  only:
    - uat
  except:
    - tags
    - schedules
  dependencies: []

e2e_integration:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/cypress/base:14.16.0
  stage: test
  only:
    - schedules
  variables:
    CYPRESS_APP_URL: http://powwowng1.zone.local:8080/
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - ui/node_modules
      - cache/Cypress
      - .cache/Cypress
  allow_failure: true
  script:
    - cd ui
    - yarn install --frozen-lockfile
    - yarn e2e || echo e2e failed
    - yarn generate:html:report
    - python cypress/flaky-test/script.py
    - cd ../
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - ui/cypress/videos
      - ui/cypress/screenshots
      - ui/TestReport
      - ui/cypress/flaky-test/flaky-tests.json
