image: pstauffer/curl:latest

variables:
  http_proxy: 'http://proxyace1.prod.extelia.fr:8080'
  https_proxy: 'http://proxyace1.prod.extelia.fr:8080'

start_ui_server_pipeline:
  stage: deploy
  script:
      - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://m2m.extelia.fr/gitlab/api/v4/projects/7/trigger/pipeline
  only:
    - master