module.exports = {
  orders: {
    total: 20,
    orders: [
      {
        creationDate: '1/15/2018',
        partnerName: 'Wikivu',
        id: 5734,
        status: 'TO_VALIDATE',
        quantity: 84,
        productName: 'SIM M2M',
        creator: 'Norby Johantges',
      },
      {
        creationDate: '6/11/2018',
        partnerName: 'Meembee',
        id: 5516,
        status: 'TO_VALIDATE',
        quantity: 38,
        productName: 'SIM M2M',
        creator: 'Raviv Caiger',
      },
      {
        creationDate: '9/17/2018',
        partnerName: 'Kaymbo',
        id: 5168,
        status: 'TO_VALIDATE',
        quantity: 66,
        productName: 'SIM M2M',
        creator: 'Dorice Bollam',
      },
      {
        creationDate: '8/27/2018',
        partnerName: 'Skippad',
        id: 5329,
        status: 'TO_VALIDATE',
        quantity: 98,
        productName: 'SIM M2M',
        creator: 'Otha Patley',
      },
      {
        creationDate: '7/4/2018',
        partnerName: 'Photofeed',
        id: 5342,
        status: 'TO_VALIDATE',
        quantity: 94,
        productName: 'SIM M2M',
        creator: 'Carrol Idwal Evans',
      },
      {
        creationDate: '1/12/2018',
        partnerName: 'Gabcube',
        id: 5912,
        status: 'TO_VALIDATE',
        quantity: 60,
        productName: 'SIM M2M',
        creator: 'Irvin MacSkeagan',
      },
      {
        creationDate: '12/15/2017',
        partnerName: 'Tambee',
        id: 5747,
        status: 'TO_VALIDATE',
        quantity: 57,
        productName: 'SIM M2M',
        creator: 'Mureil Turbayne',
      },
      {
        creationDate: '9/2/2018',
        partnerName: 'Mudo',
        id: 5838,
        status: 'TO_VALIDATE',
        quantity: 16,
        productName: 'SIM M2M',
        creator: 'Ely Farebrother',
      },
      {
        creationDate: '6/25/2018',
        partnerName: 'Rhycero',
        id: 5213,
        status: 'TO_VALIDATE',
        quantity: 30,
        productName: 'SIM M2M',
        creator: 'Jakie Gyrgorwicx',
      },
      {
        creationDate: '10/10/2018',
        partnerName: 'Thoughtsphere',
        id: 5724,
        status: 'TO_VALIDATE',
        quantity: 2,
        productName: 'SIM M2M',
        creator: 'Josy Kienzle',
      },
      {
        creationDate: '2/3/2018',
        partnerName: 'Kamba',
        id: 5310,
        status: 'TO_VALIDATE',
        quantity: 74,
        productName: 'SIM M2M',
        creator: 'Stanley Brodnecke',
      },
      {
        creationDate: '8/23/2018',
        partnerName: 'Aivee',
        id: 5166,
        status: 'TO_VALIDATE',
        quantity: 44,
        productName: 'SIM M2M',
        creator: 'Janith Wedlock',
      },
      {
        creationDate: '10/16/2018',
        partnerName: 'Skaboo',
        id: 5364,
        status: 'TO_VALIDATE',
        quantity: 92,
        productName: 'SIM M2M',
        creator: 'Bertie Semon',
      },
      {
        creationDate: '11/12/2018',
        partnerName: 'Browsezoom',
        id: 5852,
        status: 'TO_VALIDATE',
        quantity: 45,
        productName: 'SIM M2M',
        creator: 'Aila Hoffner',
      },
      {
        creationDate: '6/19/2018',
        partnerName: 'Fliptune',
        id: 5413,
        status: 'TO_VALIDATE',
        quantity: 48,
        productName: 'SIM M2M',
        creator: 'Bancroft Porrett',
      },
      {
        creationDate: '12/26/2017',
        partnerName: 'Oloo',
        id: 5639,
        status: 'TO_VALIDATE',
        quantity: 75,
        productName: 'SIM M2M',
        creator: 'Joni Mortell',
      },
      {
        creationDate: '11/21/2018',
        partnerName: 'Rhybox',
        id: 5756,
        status: 'TO_VALIDATE',
        quantity: 55,
        productName: 'SIM M2M',
        creator: 'Shamus McKeefry',
      },
      {
        creationDate: '12/18/2017',
        partnerName: 'Jabberstorm',
        id: 5382,
        status: 'TO_VALIDATE',
        quantity: 19,
        productName: 'SIM M2M',
        creator: 'Nicola Hubery',
      },
      {
        creationDate: '11/23/2018',
        partnerName: 'Fadeo',
        id: 5987,
        status: 'TO_VALIDATE',
        quantity: 16,
        productName: 'SIM M2M',
        creator: 'Laureen VanBrugh',
      },
      {
        creationDate: '2/26/2018',
        partnerName: 'Oba',
        id: 5837,
        status: 'TO_VALIDATE',
        quantity: 62,
        productName: 'SIM M2M',
        creator: 'Marc Karlolczak',
      },
    ],
  },
};
