module.exports = {
  partys: {
    total: 24,
    items: [
      {
        id: '141',
        name: '1',
        code: 'TEST PARTENAIRE',
        siren: '1',
        naf: null,
      },
      {
        id: '121',
        name: 'TEST_MULTI',
        code: 'TEST_MULTI',
        siren: null,
        naf: null,
      },
      {
        id: '101',
        name: 'A_MULTIPLE 1',
        code: 'A_MULTIPLE',
        siren: null,
        naf: null,
      },
      {
        id: '81',
        name: 'MULTI_CUSTO',
        code: '6.6666',
        siren: null,
        naf: null,
      },
      {
        id: '64',
        name: 'RAISONTEST',
        code: 'TESTEFEZF',
        siren: '465',
        naf: null,
      },
      {
        id: '62',
        name: 'TESTRAIS',
        code: 'TESTEF',
        siren: '545',
        naf: null,
      },
      {
        id: '41',
        name: 'PARTY_GDM_DELETED',
        code: '3.87198',
        siren: '54654684',
        naf: null,
      },
      {
        id: '26',
        name: 'OLOLO',
        code: 'ALOO',
        siren: '5454154',
        naf: null,
      },
      {
        id: '24',
        name: 'TEST',
        code: 'TEST LISTE',
        siren: '841695869',
        naf: null,
      },
      {
        id: '15',
        name: 'KPN FRANCE',
        code: '6.80753',
        siren: null,
        naf: null,
      },
      {
        id: '14',
        name: 'DATACET',
        code: '5.15492',
        siren: null,
        naf: null,
      },
      {
        id: '13',
        name: 'Automotive control systems',
        code: '5.15189',
        siren: null,
        naf: null,
      },
      {
        id: '12',
        name: 'Timer BV',
        code: '5.15499',
        siren: null,
        naf: null,
      },
      {
        id: '11',
        name: 'client Test',
        code: '5.65499',
        siren: null,
        naf: null,
      },
      {
        id: '10',
        name: 'Fleet',
        code: '5.17899',
        siren: null,
        naf: null,
      },
      {
        id: '9',
        name: 'Mobigard',
        code: '5.34899',
        siren: null,
        naf: null,
      },
      {
        id: '8',
        name: 'Transics',
        code: '5.32149',
        siren: null,
        naf: null,
      },
      {
        id: '7',
        name: 'GOODKAP',
        code: '1-GOODKAP',
        siren: '47545',
        naf: null,
      },
      {
        id: '6',
        name: 'ERDF',
        code: '1-HN0KO',
        siren: null,
        naf: null,
      },
      {
        id: '5',
        name: 'AUCHAN',
        code: '5.12648',
        siren: '1874165',
        naf: null,
      },
      {
        id: '4',
        name: 'Numericable',
        code: '5.12647',
        siren: null,
        naf: null,
      },
      {
        id: '3',
        name: 'EDELIA',
        code: '5.12347',
        siren: '154',
        naf: null,
      },
      {
        id: '2',
        name: 'LYRA NETWORK',
        code: '6.42661',
        siren: '434075719',
        naf: null,
      },
      {
        id: '1',
        name: 'INGENICO',
        code: '5.12345',
        siren: null,
        naf: null,
      },
    ],
  },
};
